name: pipeline
on:
  push:
    branches:
      - main
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test:unit
  build:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js v20.10.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Build
        run: npm run build
      - name: Upload bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: dist
          if-no-files-found: error
  deploy:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      hasCommitChanges: ${{ steps.commit.outputs.hasCommitChanges }}
    steps:
      - name: Checkout code on prod branch
        uses: actions/checkout@v4
        with:
          ref: prod
      - name: Delete old bundle
        run: |
          rm -rf assets
          rm index.html
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: bundle
      - name: Commit new bundle
        id: commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          echo 'hasCommitChanges=${git commit -m "Update bundle" 2>&1}' >> $GITHUB_OUTPUT ';'
      - name: Push changes
        if: steps.commit.outputs.hasCommitChanges == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TO_PUSH_ONTO_PROD }}
          branch: prod
          force: true